### ISSUE TITLE
Angular JS 2 Stable support?

### ISSUE THREAD

**Issue by refaelgold** [rocwang/storefront#1]
Hey , i want to make it work on ionic 2 - You think its possible to do it? They code will work on magento 2.1.4?

**Comment by rocwang** [comment]
@refaelgold Not familiar with Ionic 2, but I think it's definitely possible. I haven't got time to support or test it against Magento 2.1.4 and the official Angular 2.x versions.

**Comment by albertobraschi** [comment]
have you a demo from it?

**Comment by refaelgold** [comment]
i want to take it over and do pulls for this projects. i will try to make more stable version for angular js 2.4
