### ISSUE TITLE
I Want to do the same angular5

### ISSUE THREAD

**Issue by santhoshrajuvysyaraju** [rocwang/storefront#3]
Hi I Want to integrate the magento2 to angular5 but i am facing post request issue . the api will respond perfectly for get requests. but for the post requests it is showing an error like this.

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://ewalltechnologies.in/m2/ecommerce/rest/V1/customers. (Reason: CORS preflight channel did not succeed).

can you help me to solve the issue.

**Comment by rocwang** [comment]
Hi @santhoshrajuvysyaraju 

Please see https://github.com/rocwang/storefront#magento-2-rest-api

To expose the API to a client, which might be running from a different domain to your Magento instance, you need to enable
[Cross Origin Resource Sharing](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS) in your Magento's web server.

Example configuration for Apache:

    # Always set these headers.
    Header always set Access-Control-Allow-Origin "*"
    Header always set Access-Control-Allow-Methods "POST, GET, OPTIONS, DELETE, PUT"
    Header always set Access-Control-Max-Age "86400"
    Header always set Access-Control-Allow-Headers "X-Requested-With, Content-Type, Origin, Authorization, Accept, Client-Security-Token"

    # Added a rewrite to respond with a 200 SUCCESS on every OPTIONS request.
    RewriteEngine On
    RewriteCond %{REQUEST_METHOD} OPTIONS
    RewriteRule ^(.*)$ $1 [R=200,L]

**Comment by santhoshrajuvysyaraju** [comment]
Thanks that's working fine. You saved a lot of time.

**Comment by santhoshrajuvysyaraju** [comment]
Hi, I am getting this error

POST http://ewalltechnologies.in/m2/ecommerce/rest/V1/customers 500 (Internal Server Error)
